//DIFERENÇA ENTRE CONST E LET
//CONST O SEU VALOR NAO PODE SER ALTERADO E LET O SEU VALOR PODE SER ALTERADO

const numero1 = 1;
let numero2 = 2;

if(numero1 == 1) {
    numero2 = 4; //SE ESSA VARIAVAL FOSSE DO TIPO CONST DARIA ERRO PORQUE O SEU VALOR NAO PODE SER ALTERADO
}

console.log(numero2)